### PR TITLE
Add Metamask connection option

### PR DESCRIPTION
**Pull request by jagodarybacka**
Resolves https://github.com/tahowallet/dapp/issues/771

### What

Add Metamask to supported wallets 🦊 🥲

Metamask is visible only if you don't have Taho wallet installed.

image

### Testing

1. Testing Taho **without** Metamask installed
- [x] make sure you are able to connect to Taho
- [x] make sure you are able to do transactions (stake, unstake) using Taho
- [x] make sure you are able to disconnect and reconnect using Taho

2. Testing Taho **with** Metamask installed
- [x] make sure you are able to connect to Taho
- [x] make sure you are able to do transactions (stake, unstake) using Taho
- [x] make sure you are able to disconnect and reconnect using Taho

3. Testing Metamask **without** Taho installed
- [x] make sure you are able to connect to Metamask
- [x] make sure you are able to do transactions (stake, unstake) using Metamask
- [x] make sure you are able to disconnect and reconnect using Metamask
- [x] make sure selecting Taho as connection option fails gracefully

### CODE REVIEW

**Comment by VladUXUI** [comment]
Might be edge case, but if:
1 - Taho was connected (MM Disabled)
2 - Taho was Disabled - MM Enabled
It seems to break everything, as it redirects me to chrome store instantly



https://github.com/tahowallet/dapp/assets/80846886/d3f1f241-3855-4d35-b9d6-ad9996850e0e

**Comment by VladUXUI** [comment]
Another small issue,
IF> MM is connected and i change address in MM, i need to hard-refresh Subscape in order to connect another address

**Comment by michalinacienciala** [comment]
> Might be edge case, but if: 1 - Taho was connected (MM Disabled) 2 - Taho was Disabled - MM Enabled It seems to break everything, as it redirects me to chrome store instantly
> 
>  CleanShot.2023-11-29.at.18.15.57.mp4

Got the same issue. After having both MM and Taho installed (MM not connected to dapp yet, on Ethereum Mainnet, Arb Sepolia added to the chains list; Taho actively connected to dapp) I disabled the Taho plugin and reloaded the Subscape page (to test connecting to dapp with MM). I got black screen, and `Sending metamask:reload message` in dapp's logs. Switching to Arb Sepolia in MM did not make a difference. Then I noticed that Chrome blocks the pop-up window and once I allowed it to show the pop-up I was directed to Taho Google Store.

https://github.com/tahowallet/dapp/assets/78352137/b584b132-cbfd-406a-9664-529a4a39398e

Here is what I did next, that helped with the issue:
 
1. Enabled Taho extension
2. Opened Taho and disconnected from Subscape from the wallet
3. Reloaded Subscape. A Taho extension poped up asking for connecting to dapp.  chose Connect and got in to the Subscape.
4. I disconnected the wallet from dapp and got the Connect Taho to open portal view.
5. I disabled the Taho extension
6. Reloaded the dapp again, got the Connect Taho to open portal view.
7. Pressed Connect wallet. Finally got to the screen with choice for MM/Taho (Taho correctly pointing to Taho Store and MM correctly popping up the MM connection method window)

**Comment by michalinacienciala** [comment]
When I try to connect do dapp with MM on a Ethereum network I'm asked if I allow for changing the network (that's correct). But in the dapp's logs I can see a bunch of errors at that point (I'm not sure if they are expected). Once I allow, I'm successfully connected to dapp and the network changes to Arbitrum Sepolia in MM (correct).

image

**Comment by michalinacienciala** [comment]
Got an issue with staking:

1. I disabled Taho in Brave
2. Installed MM there and imported an account. Did not change networks.
3. I entered https://deploy-preview-788--taho-development.netlify.app/ and did the steps required in order to connect with MM. At the step where MM asks if I allow adding new network (Arbitrum Sepolia) to MM I saw these errors:
image
4. I allowed adding new network and got connected, entered the Island. Network in MM switched to Arbitrum Sepolia.
5. I tried to stake to Base realm (where I already had some stake), but got this error:
```
Failed to send transaction Error: underlying network changed (event="changed", network={"name":"homestead","chainId":1,"ensAddress":"0x00000000000C2E074eC69A0dFb2997BA6C7d2e1e"}, detectedNetwork={"chainId":421614,"name":"unknown"}, code=NETWORK_ERROR, version=providers/5.7.2)
    at u.makeError (index.js:224:23)
    at pe.<anonymous> (base-provider.js:998:38)
    at Generator.next (<anonymous>)
    at c (base-provider.js:5:58)
```
6. When I tried again, I was able to stake.

**Comment by michalinacienciala** [comment]
> Another small issue, IF> MM is connected and i change address in MM, i need to hard-refresh Subscape in order to connect another address

For me when I stuck in a loop when changing accounts in MM it was ok to do just a normal refresh:

https://github.com/tahowallet/dapp/assets/78352137/3fc7a73a-5f15-436c-ab21-9243b334fece

**Review by xpaczka — APPROVED** [review]
:shipit:

**Pull request merged**
